name: Trading Signal Action

on:
  issues:
    types: [opened, edited]

jobs:
  issueResponse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run Python Script
        run: python process_signal.py "${{ github.event.issue.title }}" "${{ github.event.issue.body }}"
        env:
          ALPACA_KEY: ${{ secrets.ALPACA_KEY }}
          ALPACA_SECRET: ${{ secrets.ALPACA_SECRET }}
